import { Geist, Geist_Mono } from "next/font/google";
import {
  Dancing_Script,
  Great_Vibes,
  Pacifico,
  Allura,
} from "next/font/google";

import "./globals.css";

// Default fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Signature Fonts
const dancingScript = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-dancing-script",
});

const greatVibes = Great_Vibes({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-great-vibes",
});

const pacifico = Pacifico({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-pacifico",
});

const allura = Allura({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-allura",
});

export const metadata = {
  title: "EzSignly Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${dancingScript.variable}
          ${greatVibes.variable}
          ${pacifico.variable}
          ${allura.variable}
        `}
      >
        {children}
      </body>
    </html>
  );
}
